%{
This script takes data generated by Oceanwavesim and sends is via serial
to an arduino controlling the linear rail.

Linear rail max speed is around 22mm/s. Max travel distance is around 280mm

In order to make the arduino side easier, this script actually sends the
delay between steps in microseconds.

The needed delay is calculated using this formula:
delay_us = 40396(speed^-1.004)

Where speed is in mm/s. The formula was generated by experiment. Results
can be found in OpenWave\arduino\linear_rail_driver\Step_delay2speed.xlsx


%}

num_waves = 30;
fs = 4;
dt=1/fs;
stoptime = 30; %signal length in seconds
t = (0:dt:stoptime)'; % make time x axis

original_displacement = oceanWaveSim(num_waves, 20, fs, stoptime);

plot(t, original_displacement)
hold on
[differentiated_accel, differentiated_velocity] = disp2Accel(original_displacement, t);

n = numel(original_displacement);
for i = 1:n
    disp(original_displacement(1:i))
    pause(dt)
end
